apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aks-lab-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/prabhatmore/devops-aks-project.git
    targetRevision: main
    path: argocd-manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: akslab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
