apiVersion: v1
kind: Service
metadata:
  name: aks-lab-app
  namespace: akslab
spec:
  type: ClusterIP
  selector:
    app: aks-lab-app
  ports:
    - name: http
      port: 80
      targetPort: 5000
